name: Build EndeavourOS CE Hyprland ISO

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
         # this might remove tools that are actually needed,
         # if set to "true" but frees about 6 GB
         tool-cache: false
         # all of these default to true, but feel free to set to
         # "false" if necessary for your workflow
         android: true
         dotnet: true
         haskell: true
         large-packages: true
         docker-images: true
         swap-storage: true
          
      - uses: actions/checkout@v2
      
      - name: Set current date and hour as environment variable
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
                      
      - name: Add EndeavourOS Repo
        run: bash add-EndeavourOS
        
      - name: Update packages and install archiso
        run: "pacman -Syu --noconfirm --needed archiso mkinitcpio-archiso git squashfs-tools wget sudo base-devel curl lftp yay"

      - name: preparations to build ISO
        run: bash prepare-action
      
      - name: create build user and build some packages
        run: bash prebuild-packages
    
      - name: Build ISO
        run: bash build-iso
      
      - name: Upload binaries to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "EHCE ${{ env.NOW }}"
          files: |
                 EndeavourOS-ISO/out/EndeavourOS-Community-hyprland-${{ env.NOW }}-iso.split-aa
                 EndeavourOS-ISO/out/EndeavourOS-Community-hyprland-${{ env.NOW }}-iso.split-ab
                 EndeavourOS-ISO/out/EndeavourOS-Community-hyprland-${{ env.NOW }}-iso.split-ac
          id: "EHCE"
