name: Build EndeavourOS devel ISO

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v2
      
      - name: Set current date and hour as environment variable
        run: echo "NOW=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
                      
      - name: Add EndeavourOS Repo
        run: bash add-EndeavourOS.sh
        
      - name: Update packages and install archiso
        run: "pacman -Syu --noconfirm --needed archiso mkinitcpio-archiso git squashfs-tools wget sudo base-devel curl lftp"
        
      - name: preparations to build ISO
        run: bash prepare-action.sh
        
      - name: create normal user (build) for Build Calamares git packages and prepare actions
        run: bash build-packages.sh
        
      - name: Build ISO
        run: bash build.sh

      - name: Add hour to release and tarball
        run: "cp EndeavourOS-Community-hyprland-ISO/*.log EndeavourOS-Community-hyprland-ISO/out/ && cd EndeavourOS-Community-hyprland-ISO/out && tar -czvf EndeavourOS-Community-hyprland-${{ env.NOW }}-iso.tar.gz *.sha512sum *.iso *.log"
        
      - name: Upload a backup to server_DEVEL
        run: "curl -g -k -T EndeavourOS-Community-hyprland-ISO/out/*.tar.gz -u ${{secrets.SERVER_STRING_DEVEL}}"
      
